version: '3.7'
services:
   kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    #volumes:
    # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet

   logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    container_name: logstash
    networks:
      - esnet


   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
   elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
   elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet
 
   nginx:
    image: sameersbn/nginx:1.15.3
    ports:
    - "80:80"
    volumes:
     - /srv/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    restart: always
    networks:
     - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet:
